name: Label Agent PRs

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add from-agent label for PRs from non-members
        uses: actions/github-script@v7
        with:
          script: |
            const assoc = context.payload.pull_request.author_association;
            const label = 'from-agent';
            if (assoc === 'NONE' || assoc === 'FIRST_TIMER' || assoc === 'FIRST_TIME_CONTRIBUTOR') {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [label]
              });
            }

