name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Check compilation
        run: cargo check --workspace --locked --all-targets

  test-matrix:
    name: Test Matrix
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - embedder: candle
            env:
              SURR_EMBED_PROVIDER: candle

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        env: ${{ matrix.env }}
        run: cargo test --workspace --all-features

  verify-rmcp:
    name: Verify RMCP Updates
    runs-on: macos-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Update RMCP and check
        run: |
          cargo update -p rmcp
          cargo check --locked --all-targets
